### ISSUE TITLE
Recommendations

### ISSUE THREAD

**Issue by Rickodesea** [kadir014/nova-physics#1]
I like this library and am testing it in my 2D game.  Here are some recommendations:
- I recommend including CMAKE build because it is easy to use and cross platform.  I could not build the examples with the custom build.  Keeps giving errors.  A cmake build would make it easier for me to drop it into my projects.
- I recommend using -Wall build warnings.  There were alot of errors when building.  I built it with -Wall on C99 standard.
- I recommend adding more documentation and explanation on various abstract features like constraint and awake/sleep.  There is not much understanding in the position_iters and velocity_iters field of the nv_Space_step API.
- I recommend adding more simple getting started samples.  I found the example added to be very difficult to understand.
- I recommend updating the APIs to make it more friendly to Game development.  I am working on a flat plane 2D game and I had to manually zero the gravity variable of the Space object because that was not desired in my Game.  Making the gravity force optional in the nv_Space_new() API would have been better.  I had to write my own friction logic and clamp to zero logic (once the velocity is under a certain value, set it to zero) to make the feel of the physics more 2D game friendly.  Would be awesome to include this as additional API.

**Comment by kadir014** [comment]
I really appreciate your feedback. All of your suggestions are added to my TODO list and I will be working on it :)

About the last suggestion, Box2D has a friction constraint to achieve that. I might do something similar.
