### ISSUE TITLE
bunch of warnings

### ISSUE THREAD

**Issue by iamwhosiam** [kadir014/nova-physics#2]
You should compile with warnings turned up, you got a bunch of little errors.

example:

in nv_Space_broadphase you have a for loop going over space->bodies->size using 'j' and then inside that for loop you use 'j' again, and you do that a couple times.

also, there's quiet a few instances of signed / unsigned mismatching in for loops

**Comment by kadir014** [comment]
Thanks for reporting in.

This is actually one of the reasons why there hasn't been any commits or updates for a while. I'm working on refactoring and general overhauls. ~~_And a possible CMake support_~~

You can open a new issue if you encounter a bug or a compile error 👍
